In [1]:
import numpy as np
# from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd

# Теория

### 1.1 Аналитическое решение линейной регрессии
Мы ищем такие веса, чтобы предсказания были максимально близко к настоящим значениям.
Если записать все объекты в матрицу X, а ответы в вектор y, то решение можно получить напрямую формулой:
"веса = (X транспонированная * X) в обратной * X транспонированная * y".
Идея: это способ найти лучшие веса без итераций (без градиентного спуска).

### 1.2 Что меняется при добавлении L1 и L2 регуляризации
Регуляризация добавляет штраф к функции ошибки, чтобы веса не становились слишком большими.
- L2 (Ridge): штрафует большие веса, делает модель стабильнее, особенно если признаки похожи друг на друга.
- L1 (Lasso): заставляет часть весов стать ровно 0, выбрасывая часть признаков.
- ElasticNet: сочетает L1 и L2, обычно стабильнее предыдущих и тоже умеет занулять часть весов.

### 1.3 Почему L1 используют для отбора признаков
L1 штраф устроен так, что модель зануляет слабые признаки полностью.
В итоге часть весов становится ровно 0, и эти признаки можно считать неиспользуемыми.

### 1.4 Как теми же моделями учить нелинейные зависимости
Модель остается линейной по весам, но можно сделать признаки нелинейными.
Пример: вместо x подать x, x^2, x^3, x1*x2 и т.д.
Тогда линейная модель на таких признаках сможет описывать нелинейные формы.


###  4. Что такое детерминированная модель и как сделать SGD детерминированным
Детерминированная модель: при одинаковых данных и настройках дает одинаковый результат при каждом запуске.
Чтобы SGD был детерминированным:
- зафиксировать random_state для numpy и для самого алгоритма
- не перемешивать данные случайно, или перемешивать с фиксированным seed
- фиксировать начальные веса через seed, либо делать их одинаковыми, например нулями
- фиксировать порядок батчей и размер батча


### 6. Где нормализация обязательна, а где нет
Нормализация обязательна/полезна:
- линейные модели с регуляризацией (Ridge, Lasso, ElasticNet)
- модели на расстояниях (kNN, k-means)
- градиентные методы, где скорость обучения зависит от масштаба признаков
- когда признаки в разных единицах (метры и миллионы рублей)

Нормализация обычно не нужна в деревьях и всех их проявлениях (лесах и бустингах)

# Preprocessing

In [2]:
train = pd.read_json('data/train.json')
test = pd.read_json('data/test.json')

In [3]:
l, r = train.price.quantile([0.05, 0.95])
train = train.loc[(train.price>=l)&(train.price<=r)]

атата - незя так поступать... но там выбора не было

In [4]:
l, r = test.price.quantile([0.05, 0.95])
test = test.loc[(test.price>=l)&(test.price<=r)]

In [5]:
train.info()

<class 'pandas.DataFrame'>
Index: 44612 entries, 4 to 124009
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bathrooms        44612 non-null  float64
 1   bedrooms         44612 non-null  int64
 2   building_id      44612 non-null  str
 3   created          44612 non-null  str
 4   description      44612 non-null  str
 5   display_address  44612 non-null  str
 6   features         44612 non-null  object
 7   latitude         44612 non-null  float64
 8   listing_id       44612 non-null  int64
 9   longitude        44612 non-null  float64
 10  manager_id       44612 non-null  str
 11  photos           44612 non-null  object
 12  price            44612 non-null  int64
 13  street_address   44612 non-null  str
 14  interest_level   44612 non-null  str
dtypes: float64(3), int64(3), object(2), str(7)
memory usage: 5.4+ MB

In [6]:
train.features.head()

4     [Dining Room, Pre-War, Laundry in Building, Di...
6     [Doorman, Elevator, Laundry in Building, Dishw...
9     [Doorman, Elevator, Laundry in Building, Laund...
10                                                   []
15    [Doorman, Elevator, Fitness Center, Laundry in...
Name: features, dtype: object

In [7]:
# features = []
# for string in train.features: 
#     features = features +[elem.strip() for elem in list(string)]
# len(features)

In [8]:
features = [elem.strip() for string in train.features for elem in string ]
len(features)

242337

In [9]:
features = pd.Series(features)
names = features.value_counts().head(20)
names

Elevator               23501
Hardwood Floors        21623
Cats Allowed           21331
Dogs Allowed           19942
Doorman                19003
Dishwasher             18803
No Fee                 16710
Laundry in Building    15042
Fitness Center         12064
Pre-War                 8269
Laundry in Unit         7508
Roof Deck               6046
Outdoor Space           4721
Dining Room             4227
High Speed Internet     3957
Balcony                 2668
Laundry In Building     2430
Swimming Pool           2375
New Construction        2328
Terrace                 1947
Name: count, dtype: int64

In [ ]:
keys = names.index.tolist() 
cols = {f"has_{k}": train.features.map(lambda string, t_k=k: t_k in string).astype("int8") for k in keys}
df = pd.DataFrame()
df = df.assign(**cols)
df

,has_Elevator,has_Hardwood Floors,has_Cats Allowed,has_Dogs Allowed,has_Doorman,has_Dishwasher,has_No Fee,has_Laundry in Building,has_Fitness Center,has_Pre-War,has_Laundry in Unit,has_Roof Deck,has_Outdoor Space,has_Dining Room,has_High Speed Internet,has_Balcony,has_Laundry In Building,has_Swimming Pool,has_New Construction,has_Terrace
4,0,1,1,1,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0
6,1,1,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0
9,1,1,0,0,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124000,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
124002,1,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
124004,1,1,1,1,0,1,1,1,0,1,1,0,0,1,0,0,0,0,0,0
124008,0,0,0,0,0,1,1,0,0,1,1,0,1,0,0,0,0,0,0,0
124009,1,1,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0

In [11]:
data = pd.concat([df, train.bathrooms.astype('int8'), train.bedrooms.astype('int8')], axis=1)
data.info()

<class 'pandas.DataFrame'>
Index: 44612 entries, 4 to 124009
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   has_Elevator             44612 non-null  int8
 1   has_Hardwood Floors      44612 non-null  int8
 2   has_Cats Allowed         44612 non-null  int8
 3   has_Dogs Allowed         44612 non-null  int8
 4   has_Doorman              44612 non-null  int8
 5   has_Dishwasher           44612 non-null  int8
 6   has_No Fee               44612 non-null  int8
 7   has_Laundry in Building  44612 non-null  int8
 8   has_Fitness Center       44612 non-null  int8
 9   has_Pre-War              44612 non-null  int8
 10  has_Laundry in Unit      44612 non-null  int8
 11  has_Roof Deck            44612 non-null  int8
 12  has_Outdoor Space        44612 non-null  int8
 13  has_Dining Room          44612 non-null  int8
 14  has_High Speed Internet  44612 non-null  int8
 15  has_Balcony              44612 non-null  int8
 16  has_Laundry In Building  44612 non-null  int8
 17  has_Swimming Pool        44612 non-null  int8
 18  has_New Construction     44612 non-null  int8
 19  has_Terrace              44612 non-null  int8
 20  bathrooms                44612 non-null  int8
 21  bedrooms                 44612 non-null  int8
dtypes: int8(22)
memory usage: 1.3 MB

In [12]:
x_train = data
y_train = train.price
y_train.head()

4     2400
6     3800
9     3495
10    3000
15    2795
Name: price, dtype: int64

#### Препроцессинг для test

In [13]:
test_cols = {f"has_{k}": test.features.map(lambda string, t_k=k: t_k in string).astype("int8") for k in keys}
test_df = pd.DataFrame()
test_df = test_df.assign(**test_cols)
test_data = pd.concat([test_df, test.bathrooms.astype('int8'), test.bedrooms.astype('int8')], axis=1)
x_test = test_data
y_test = test.price
test_data.info()

<class 'pandas.DataFrame'>
Index: 67467 entries, 0 to 124010
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   has_Elevator             67467 non-null  int8
 1   has_Hardwood Floors      67467 non-null  int8
 2   has_Cats Allowed         67467 non-null  int8
 3   has_Dogs Allowed         67467 non-null  int8
 4   has_Doorman              67467 non-null  int8
 5   has_Dishwasher           67467 non-null  int8
 6   has_No Fee               67467 non-null  int8
 7   has_Laundry in Building  67467 non-null  int8
 8   has_Fitness Center       67467 non-null  int8
 9   has_Pre-War              67467 non-null  int8
 10  has_Laundry in Unit      67467 non-null  int8
 11  has_Roof Deck            67467 non-null  int8
 12  has_Outdoor Space        67467 non-null  int8
 13  has_Dining Room          67467 non-null  int8
 14  has_High Speed Internet  67467 non-null  int8
 15  has_Balcony              67467 non-null  int8
 16  has_Laundry In Building  67467 non-null  int8
 17  has_Swimming Pool        67467 non-null  int8
 18  has_New Construction     67467 non-null  int8
 19  has_Terrace              67467 non-null  int8
 20  bathrooms                67467 non-null  int8
 21  bedrooms                 67467 non-null  int8
dtypes: int8(22)
memory usage: 1.9 MB

# Linear Model implementation

In [ ]:
class my_LinearRegresion:
    def __init__(self, lr = 0.01, iterations = 1000, batch_size = 512):
        self.weights_ = None
        self.bias_ = 0
        self.lr = lr
        self.iterations = iterations
        self.batch_size = batch_size
        self.rng = np.random.default_rng(42)

    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y)
        l, f = X.shape

        w = np.zeros(f)
        b, lr = self.bias_, self.lr

        for i in range(self.iterations):
            for X_batch, y_batch in self.generate_batches(X, y):
                func = X_batch @ w + b
                error = 2*(func - y_batch)
                desc_w = (X_batch.T @ error) / (2 * len(y_batch))
                desc_b = error.mean()
                w = w - lr * desc_w
                b = b - lr * desc_b
            
        self.weights_, self.bias_ = w,b
        return self

    def generate_batches(self, X, y):
        assert len(X) == len(y)

        batch_size = self.batch_size
        X = np.array(X)
        y = np.array(y)

        idx = np.arange(len(X))
        self.rng.shuffle(idx)

        for batch_start in range(0, len(X), batch_size):
            batch_idx = idx[batch_start:batch_start+batch_size]
            yield X[batch_idx], y[batch_idx]


    def fit_BGD(self, x, y):
        x = np.asarray(x)
        y = np.asarray(y)
        l, f = x.shape

        w = np.zeros(f)
        b, lr = self.bias_, self.lr

        for i in range(self.iterations):
            func = x @ w + b
            error = 2*(func - y)
            desc_w = (x.T @ error) / l
            desc_b = error.mean()
            w = w - lr * desc_w
            b = b - lr * desc_b
            
        self.weights_, self.bias_ = w,b
        return self


    def predict(self, x):
        x = np.asarray(x)
        pred = x @ self.weights_ + self.bias_
        return pred

### Metrics implementation

In [15]:
def R2(y, pred):
    y = np.asarray(y)
    pred = np.asarray(pred)
    mean = np.mean(y)
    S_error = np.sum((y-pred)**2)
    N_error = np.sum((y-mean)**2)

    if N_error == 0:
        return 1 if S_error == 0 else 0
    R2 = 1 - S_error/N_error
    
    return R2

def MAE(y, pred): 
    return np.mean(np.abs(y - pred))

def RMSE(y, pred):
    return np.sqrt(np.mean((y - pred)**2))

### Fit n Predict

In [16]:
my_lr = my_LinearRegresion()
my_lr.fit(x_train, y_train)

In [17]:
sk_lr = linear_model.SGDRegressor(random_state=42, penalty=None, tol=None)
sk_lr.fit(x_train, y_train)

SGDRegressor(penalty=None, random_state=42, tol=None)

### MAE

In [18]:
MAE_scores  = pd.DataFrame(columns=["model", "train", "test"])

MAE_scores.loc[len(MAE_scores)] = ["my_lr", MAE(y_train, my_lr.predict(x_train)), MAE(y_test, my_lr.predict(x_test))]
MAE_scores.loc[len(MAE_scores)] = ["sk_lr", MAE(y_train, sk_lr.predict(x_train)), MAE(y_test, sk_lr.predict(x_test))]
MAE_scores

   model       train        test
0  my_lr  594.907434  600.012409
1  sk_lr  593.250954  598.410908

### RMSE

In [19]:
RMSE_scores = pd.DataFrame(columns=["model", "train", "test"])

RMSE_scores.loc[len(RMSE_scores)] = ["my_lr", RMSE(y_train, my_lr.predict(x_train)), RMSE(y_test, my_lr.predict(x_test))]
RMSE_scores.loc[len(RMSE_scores)] = ["sk_lr", RMSE(y_train, sk_lr.predict(x_train)), RMSE(y_test, sk_lr.predict(x_test))]
RMSE_scores

   model       train        test
0  my_lr  785.994621  882.120155
1  sk_lr  786.039632  881.334800

### R2

In [20]:
R2_scores  = pd.DataFrame(columns=["model", "train", "test"])

R2_scores.loc[len(R2_scores)] = ["my_lr", R2(y_train, my_lr.predict(x_train)), R2(y_test, my_lr.predict(x_test))]
R2_scores.loc[len(R2_scores)] = ["sk_lr", R2(y_train, sk_lr.predict(x_train)), R2(y_test, sk_lr.predict(x_test))]
R2_scores

   model     train      test
0  my_lr  0.511039  0.381255
1  sk_lr  0.510983  0.382357

# Ridge, Lasso, ElasticNet implementation

## Lasso

In [21]:
class my_Lasso:

    def __init__(self, alpha = 1, lr = 0.01, iterations = 1000, batch_size = 512):
        self.weights_ = None
        self.bias_ = 0
        self.lr = lr
        self.alpha =alpha
        self.iterations = iterations
        self.batch_size = batch_size
        self.rng = np.random.default_rng(42)


    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y)
        l, f = X.shape

        w = np.zeros(f)
        b, lr, alpha= self.bias_, self.lr, self.alpha

        for i in range(self.iterations):
            for X_batch, y_batch in self.generate_batches(X, y):
                func = X_batch @ w + b
                error = 2*(func - y_batch)
                desc_w = (X_batch.T @ error) / (2* len(y_batch)) + alpha * np.sign(w)
                desc_b = error.mean()

                w = w - lr * desc_w
                b = b - lr * desc_b
    
        self.weights_, self.bias_ = w,b
        return self


    def generate_batches(self, X, y):
        assert len(X) == len(y)

        batch_size = self.batch_size
        X = np.array(X)
        y = np.array(y)

        idx = np.arange(len(X))
        self.rng.shuffle(idx)

        for batch_start in range(0, len(X), batch_size):
            batch_idx = idx[batch_start:batch_start+batch_size]
            yield X[batch_idx], y[batch_idx]


    def fit_BGD(self, x, y):
        x = np.asarray(x)
        y = np.asarray(y)
        l, f = x.shape

        w = np.zeros(f)
        b, lr, alpha = self.bias_, self.lr, self.alpha

        for i in range(self.iterations):
            func = x @ w + b
            error = 2*(func - y)
            desc_w = (x.T @ error) / l
            desc_b = error.mean()

            desc_reg = alpha * np.sign(w)
            desc_w = desc_w + desc_reg

            w = w - lr * desc_w
            b = b - lr * desc_b

        self.weights_, self.bias_ = w,b
        return self


    def predict(self, x):
        x = np.asarray(x)
        pred = x @ self.weights_ + self.bias_
        return pred

In [22]:
my_Lasso = my_Lasso()
my_Lasso.fit(x_train, y_train)

In [23]:
sk_Lasso = linear_model.Lasso(alpha=1)
sk_Lasso.fit(x_train, y_train)

Lasso(alpha=1)

### MAE

In [24]:
MAE_scores.loc[len(MAE_scores)] = ["my_Lasso", MAE(y_train, my_Lasso.predict(x_train)), MAE(y_test, my_Lasso.predict(x_test))]
MAE_scores.loc[len(MAE_scores)] = ["sk_Lasso", MAE(y_train, sk_Lasso.predict(x_train)), MAE(y_test, sk_Lasso.predict(x_test))]
MAE_scores

      model       train        test
0     my_lr  594.907434  600.012409
1     sk_lr  593.250954  598.410908
2  my_Lasso  595.146849  600.411714
3  sk_Lasso  594.303256  599.583917

### RMSE

In [25]:
RMSE_scores.loc[len(RMSE_scores)] = ["my_Lasso", RMSE(y_train, my_Lasso.predict(x_train)), RMSE(y_test, my_Lasso.predict(x_test))]
RMSE_scores.loc[len(RMSE_scores)] = ["sk_Lasso", RMSE(y_train, sk_Lasso.predict(x_train)), RMSE(y_test, sk_Lasso.predict(x_test))]
RMSE_scores

      model       train        test
0     my_lr  785.994621  882.120155
1     sk_lr  786.039632  881.334800
2  my_Lasso  786.176135  881.199352
3  sk_Lasso  786.149790  880.791767

### R2

In [26]:
R2_scores.loc[len(R2_scores)] = ["my_Lasso", R2(y_train, my_Lasso.predict(x_train)), R2(y_test, my_Lasso.predict(x_test))]
R2_scores.loc[len(R2_scores)] = ["sk_Lasso", R2(y_train, sk_Lasso.predict(x_train)), R2(y_test, sk_Lasso.predict(x_test))]
R2_scores

      model     train      test
0     my_lr  0.511039  0.381255
1     sk_lr  0.510983  0.382357
2  my_Lasso  0.510813  0.382546
3  sk_Lasso  0.510846  0.383117

## Ridge

In [27]:
class my_Ridge:

    def __init__(self, alpha = 0.01, lr = 0.01, iterations = 1000, batch_size = 512):
        self.weights_ = None
        self.bias_ = 0
        self.lr = lr
        self.alpha =alpha
        self.iterations = iterations
        self.batch_size = batch_size
        self.rng = np.random.default_rng(42)


    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y)
        l, f = X.shape

        w = np.zeros(f)
        b, lr, alpha= self.bias_, self.lr, self.alpha

        for i in range(self.iterations):
            for X_batch, y_batch in self.generate_batches(X, y):
                func = X_batch @ w + b
                error = 2*(func - y_batch)
                desc_w = (X_batch.T @ error) / (2 * len(y_batch)) + alpha * w
                desc_b = error.mean()

                w = w - lr * desc_w
                b = b - lr * desc_b
            
        self.weights_, self.bias_ = w,b
        return self
    

    def generate_batches(self, X, y):
        assert len(X) == len(y)

        batch_size = self.batch_size
        X = np.array(X)
        y = np.array(y)

        idx = np.arange(len(X))
        self.rng.shuffle(idx)

        for batch_start in range(0, len(X), batch_size):
            batch_idx = idx[batch_start:batch_start+batch_size]
            yield X[batch_idx], y[batch_idx]


    def fit_BGD(self, x, y):
        x = np.asarray(x)
        y = np.asarray(y)
        l, f = x.shape

        w = np.zeros(f)
        b, lr, alpha = self.bias_, self.lr, self.alpha

        for i in range(self.iterations):
            func = x @ w + b
            error = 2*(func - y)
            desc_w = (x.T @ error) / l
            desc_b = error.mean()
            desc_w = desc_w + 2 * alpha * w

            w = w - lr * desc_w
            b = b - lr * desc_b
            
        self.weights_, self.bias_ = w,b
        return self


    def predict(self, x):
        x = np.asarray(x)
        pred = x @ self.weights_ + self.bias_
        return pred

In [28]:
my_Ridge = my_Ridge()
my_Ridge.fit(x_train,y_train)
sk_Ridge = linear_model.Ridge(alpha=0.01)
sk_Ridge.fit(x_train, y_train)

Ridge(alpha=0.01)

## MAE

In [29]:
MAE_scores.loc[len(MAE_scores)] = ["my_Ridge", MAE(y_train, my_Ridge.predict(x_train)), MAE(y_test, my_Ridge.predict(x_test))]
MAE_scores.loc[len(MAE_scores)] = ["sk_Ridge", MAE(y_train, sk_Ridge.predict(x_train)), MAE(y_test, sk_Ridge.predict(x_test))]
MAE_scores

      model       train        test
0     my_lr  594.907434  600.012409
1     sk_lr  593.250954  598.410908
2  my_Lasso  595.146849  600.411714
3  sk_Lasso  594.303256  599.583917
4  my_Ridge  596.316804  601.409992
5  sk_Ridge  594.060545  599.192951

## RMSE

In [30]:
RMSE_scores.loc[len(RMSE_scores)] = ["my_Ridge", RMSE(y_train, my_Ridge.predict(x_train)), RMSE(y_test, my_Ridge.predict(x_test))]
RMSE_scores.loc[len(RMSE_scores)] = ["sk_Ridge", RMSE(y_train, sk_Ridge.predict(x_train)), RMSE(y_test, sk_Ridge.predict(x_test))]
RMSE_scores

      model       train        test
0     my_lr  785.994621  882.120155
1     sk_lr  786.039632  881.334800
2  my_Lasso  786.176135  881.199352
3  sk_Lasso  786.149790  880.791767
4  my_Ridge  786.617639  870.881448
5  sk_Ridge  785.955878  881.692145

## R2

In [31]:
R2_scores.loc[len(R2_scores)] = ["my_Ridge", R2(y_train, my_Ridge.predict(x_train)), R2(y_test, my_Ridge.predict(x_test))]
R2_scores.loc[len(R2_scores)] = ["sk_Ridge", R2(y_train, sk_Ridge.predict(x_train)), R2(y_test, sk_Ridge.predict(x_test))]
R2_scores

      model     train      test
0     my_lr  0.511039  0.381255
1     sk_lr  0.510983  0.382357
2  my_Lasso  0.510813  0.382546
3  sk_Lasso  0.510846  0.383117
4  my_Ridge  0.510263  0.396921
5  sk_Ridge  0.511087  0.381856

In [32]:
class my_ElasticNet:

    def __init__(self, alpha = 1, l1_ratio = 0.3, lr = 0.01, iterations = 1000, batch_size = 512):
        self.weights_ = None
        self.bias_ = 0
        self.lr = lr
        self.alpha =alpha
        self.iterations = iterations
        self.batch_size = batch_size
        self.rng = np.random.default_rng(42)
        self.l1_ratio = l1_ratio


    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y)
        l, f = X.shape

        w = np.zeros(f)
        b, lr, alpha, l1_ratio= self.bias_, self.lr, self.alpha, self.l1_ratio

        alpha1 = alpha * l1_ratio
        alpha2 = alpha - alpha1

        for i in range(self.iterations):
            for X_batch, y_batch in self.generate_batches(X, y):
                func = X_batch @ w + b
                error = 2*(func - y_batch)
                desc_w = (X_batch.T @ error) / (2*len(y_batch)) + alpha1 * np.sign(w) +  alpha2 * w
                desc_b = error.mean()

                w = w - lr * desc_w
                b = b - lr * desc_b
            
        self.weights_, self.bias_ = w,b
        return self


    def generate_batches(self, X, y):
        assert len(X) == len(y)

        batch_size = self.batch_size
        X = np.array(X)
        y = np.array(y)

        idx = np.arange(len(X))
        self.rng.shuffle(idx)

        for batch_start in range(0, len(X), batch_size):
            batch_idx = idx[batch_start:batch_start+batch_size]
            yield X[batch_idx], y[batch_idx]


    def fit_BGD(self, x, y):
        x = np.asarray(x)
        y = np.asarray(y)
        l, f = x.shape

        w = np.zeros(f)
        b, lr, alpha, l1_ratio= self.bias_, self.lr, self.alpha, self.l1_ratio

        alpha1 = alpha * l1_ratio
        alpha2 = alpha - alpha1

        for i in range(self.iterations):
            func = x @ w + b
            error = 2*(func - y)
            desc_w = (x.T @ error) / l
            desc_b = error.mean()
            desc_w = desc_w + + alpha1 * np.sign(w) +  alpha2 * w

            w = w - lr * desc_w
            b = b - lr * desc_b
            
        self.weights_, self.bias_ = w,b
        return self


    def predict(self, x):
        x = np.asarray(x)
        pred = x @ self.weights_ + self.bias_
        return pred

In [33]:
my_ElasticNet = my_ElasticNet(alpha=1, l1_ratio=0.3)
my_ElasticNet.fit(x_train, y_train)
sk_ElasticNet = linear_model.ElasticNet(alpha=1, l1_ratio=0.3)
sk_ElasticNet.fit(x_train, y_train)

ElasticNet(alpha=1, l1_ratio=0.3)

## MAE

In [34]:
MAE_scores.loc[len(MAE_scores)] = ["my_ElasticNet", MAE(y_train, my_ElasticNet.predict(x_train)), MAE(y_test, my_ElasticNet.predict(x_test))]
MAE_scores.loc[len(MAE_scores)] = ["sk_ElasticNet", MAE(y_train, sk_ElasticNet.predict(x_train)), MAE(y_test, sk_ElasticNet.predict(x_test))]
MAE_scores

           model       train        test
0          my_lr  594.907434  600.012409
1          sk_lr  593.250954  598.410908
2       my_Lasso  595.146849  600.411714
3       sk_Lasso  594.303256  599.583917
4       my_Ridge  596.316804  601.409992
5       sk_Ridge  594.060545  599.192951
6  my_ElasticNet  701.097048  703.729158
7  sk_ElasticNet  699.633142  702.186705

## RMSE

In [35]:
RMSE_scores.loc[len(RMSE_scores)] = ["my_ElasticNet", RMSE(y_train, my_ElasticNet.predict(x_train)), RMSE(y_test, my_ElasticNet.predict(x_test))]
RMSE_scores.loc[len(RMSE_scores)] = ["sk_ElasticNet", RMSE(y_train, sk_ElasticNet.predict(x_train)), RMSE(y_test, sk_ElasticNet.predict(x_test))]
RMSE_scores

           model       train        test
0          my_lr  785.994621  882.120155
1          sk_lr  786.039632  881.334800
2       my_Lasso  786.176135  881.199352
3       sk_Lasso  786.149790  880.791767
4       my_Ridge  786.617639  870.881448
5       sk_Ridge  785.955878  881.692145
6  my_ElasticNet  892.778446  897.479246
7  sk_ElasticNet  894.535637  899.007504

## R2

In [36]:
R2_scores.loc[len(R2_scores)] = ["my_ElasticNet", R2(y_train, my_ElasticNet.predict(x_train)), R2(y_test, my_ElasticNet.predict(x_test))]
R2_scores.loc[len(R2_scores)] = ["sk_ElasticNet", R2(y_train, sk_ElasticNet.predict(x_train)), R2(y_test, sk_ElasticNet.predict(x_test))]
R2_scores

           model     train      test
0          my_lr  0.511039  0.381255
1          sk_lr  0.510983  0.382357
2       my_Lasso  0.510813  0.382546
3       sk_Lasso  0.510846  0.383117
4       my_Ridge  0.510263  0.396921
5       sk_Ridge  0.511087  0.381856
6  my_ElasticNet  0.369155  0.359521
7  sk_ElasticNet  0.366669  0.357338

# Нормализация

## Математические формулы скейлеров
### MinMaxScaler
X_std = (X - X.min) / (X.max - X.min)  
X_scaled = X_std * (b - a) + a  

X - вектор признака  
X.min - минимальное значение признака
X.max - максимальное значение признака  
X_std - признак отскаллированный в диапазон [0, 1]
X_scaled - признак отскаллированный в заданный диапазон, по дефолту [0, 1]
[a, b] - границы пользовательского интервала  

### StandartScaler
z = (x - u) / s  
x — значение признака у конкретного объекта (одно число)  
u — среднее (mean) этого признака по обучающей выборке  
s — стандартное отклонение (standard deviation) этого признака по обучающей выборке  
s = sqrt( (1/n) · summ ((x − u)^2))  
z — результат стандартизации

In [37]:
class myPreprocessing: 
    def __init__(self):
        pass
    def MinMaxScaler(self, X, columns, custom_range = (0.0, 1.0)):
        scaled_data = pd.DataFrame(index=X.index)
        a, b = custom_range
        for col in columns:
            col_min, col_max = X[col].min(), X[col].max()
            x_range = col_max-col_min
            if x_range == 0 or pd.isna(x_range):
                scaled_data[col] = a
            else:
                scaled_data[col] = (X[col] - col_min) / x_range * (b - a) + a
        return scaled_data
    def StandartScaler(self, X, columns):
        z = pd.DataFrame(index=X.index)
        for col in columns:
            s = np.std(X[col], ddof=0) # ddof чтобы делили на N и сходилось с sklearn
            if s == 0 or pd.isna(s):
                z[col] = 0.0 
            else:
                z[col] = (X[col] - X[col].mean())/s
        return z

In [38]:
scaler = myPreprocessing()
sk_minmax = MinMaxScaler()
sk_standart = StandardScaler()

In [39]:
scaled_x_train = scaler.MinMaxScaler(x_train, columns=x_train.columns)
scaled_x_train.head()

,has_Elevator,has_Hardwood Floors,has_Cats Allowed,has_Dogs Allowed,has_Doorman,has_Dishwasher,has_No Fee,has_Laundry in Building,has_Fitness Center,has_Pre-War,...,has_Outdoor Space,has_Dining Room,has_High Speed Internet,has_Balcony,has_Laundry In Building,has_Swimming Pool,has_New Construction,has_Terrace,bathrooms,bedrooms
4,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.125
6,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.250
9,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.250
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.375
15,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.000

In [40]:
sk_x_train = sk_minmax.fit_transform(X = x_train)
sk_x_train = pd.DataFrame(sk_x_train)
sk_x_train.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.125
1,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.250
2,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.250
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.375
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.000

In [41]:
st_scaled_x_train = scaler.StandartScaler(x_train, x_train.columns)
st_scaled_x_train

,has_Elevator,has_Hardwood Floors,has_Cats Allowed,has_Dogs Allowed,has_Doorman,has_Dishwasher,has_No Fee,has_Laundry in Building,has_Fitness Center,has_Pre-War,...,has_Outdoor Space,has_Dining Room,has_High Speed Internet,has_Balcony,has_Laundry In Building,has_Swimming Pool,has_New Construction,has_Terrace,bathrooms,bedrooms
4,-1.055088,1.031103,1.044709,1.112244,-0.861420,1.171580,-0.773875,1.402080,-0.608812,2.096447,...,-0.344017,3.090964,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,-0.476958
6,0.947788,1.031103,-0.957205,-0.899083,1.160874,1.171580,1.292199,1.402080,-0.608812,-0.476998,...,-0.344017,-0.323524,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,0.462304
9,0.947788,1.031103,-0.957205,-0.899083,1.160874,1.171580,-0.773875,1.402080,-0.608812,-0.476998,...,-0.344017,-0.323524,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,0.462304
10,-1.055088,-0.969835,-0.957205,-0.899083,-0.861420,-0.853548,-0.773875,-0.713226,-0.608812,-0.476998,...,-0.344017,-0.323524,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,1.401566
15,0.947788,-0.969835,-0.957205,-0.899083,1.160874,-0.853548,-0.773875,1.402080,1.642542,-0.476998,...,-0.344017,-0.323524,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,-1.416220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124000,0.947788,1.031103,-0.957205,-0.899083,-0.861420,1.171580,-0.773875,-0.713226,-0.608812,-0.476998,...,-0.344017,-0.323524,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,1.401566
124002,0.947788,-0.969835,1.044709,1.112244,1.160874,-0.853548,1.292199,-0.713226,-0.608812,-0.476998,...,-0.344017,-0.323524,-0.311979,-0.252207,4.166395,-0.237129,-0.234641,-0.213623,-0.382663,0.462304
124004,0.947788,1.031103,1.044709,1.112244,-0.861420,1.171580,1.292199,1.402080,-0.608812,2.096447,...,-0.344017,3.090964,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,-0.476958
124008,-1.055088,-0.969835,-0.957205,-0.899083,-0.861420,1.171580,1.292199,-0.713226,-0.608812,2.096447,...,2.906836,-0.323524,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,0.462304
124009,0.947788,1.031103,-0.957205,-0.899083,-0.861420,1.171580,1.292199,1.402080,-0.608812,-0.476998,...,-0.344017,3.090964,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,1.401566

In [42]:
skst_x_train = sk_standart.fit_transform(x_train)
pd.DataFrame(skst_x_train).head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,-1.055088,1.031103,1.044709,1.112244,-0.861420,1.171580,-0.773875,1.402080,-0.608812,2.096447,...,-0.344017,3.090964,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,-0.476958
1,0.947788,1.031103,-0.957205,-0.899083,1.160874,1.171580,1.292199,1.402080,-0.608812,-0.476998,...,-0.344017,-0.323524,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,0.462304
2,0.947788,1.031103,-0.957205,-0.899083,1.160874,1.171580,-0.773875,1.402080,-0.608812,-0.476998,...,-0.344017,-0.323524,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,0.462304
3,-1.055088,-0.969835,-0.957205,-0.899083,-0.861420,-0.853548,-0.773875,-0.713226,-0.608812,-0.476998,...,-0.344017,-0.323524,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,1.401566
4,0.947788,-0.969835,-0.957205,-0.899083,1.160874,-0.853548,-0.773875,1.402080,1.642542,-0.476998,...,-0.344017,-0.323524,-0.311979,-0.252207,-0.240016,-0.237129,-0.234641,-0.213623,-0.382663,-1.416220

In [43]:
scaled_x_test = scaler.MinMaxScaler(x_test, x_test.columns)
st_scaled_x_test = scaler.StandartScaler(x_test, x_test.columns)

# предсказания после стандартизации

## MinMax

In [44]:
models = {
    "my_lr": my_lr,
    "my_Ridge": my_Ridge,
    "my_Lasso": my_Lasso,
    "my_ElasticNet": my_ElasticNet,
}

for name, model in models.items():
    model.fit(scaled_x_train, y_train)

    y_pred_train = model.predict(scaled_x_train)
    y_pred_test = model.predict(scaled_x_test)

    MAE_scores.loc[len(MAE_scores)] = [f"MinMax_{name}", MAE(y_train, y_pred_train), MAE(y_test, y_pred_test)]
    RMSE_scores.loc[len(RMSE_scores)] = [f"MinMax_{name}", RMSE(y_train, y_pred_train), RMSE(y_test, y_pred_test)]
    R2_scores.loc[len(R2_scores)] = [f"MinMax_{name}", R2(y_train, y_pred_train), R2(y_test, y_pred_test)]

In [45]:
y_pred_train = sk_ElasticNet.predict(scaled_x_train)
y_pred_test = sk_ElasticNet.predict(scaled_x_test)
a = [f"MinMax_{name}", MAE(y_train, y_pred_train), MAE(y_test, y_pred_test)]
a

['MinMax_my_ElasticNet',
 np.float64(868.2868111168941),
 np.float64(864.0511119631543)]

In [46]:
MAE_scores

                   model       train        test
0                  my_lr  594.907434  600.012409
1                  sk_lr  593.250954  598.410908
2               my_Lasso  595.146849  600.411714
3               sk_Lasso  594.303256  599.583917
4               my_Ridge  596.316804  601.409992
5               sk_Ridge  594.060545  599.192951
6          my_ElasticNet  701.097048  703.729158
7          sk_ElasticNet  699.633142  702.186705
8           MinMax_my_lr  603.465182  683.826811
9        MinMax_my_Ridge  663.750293  663.398592
10       MinMax_my_Lasso  605.809775  669.616592
11  MinMax_my_ElasticNet  847.943197  846.829994

In [47]:
RMSE_scores

                   model        train         test
0                  my_lr   785.994621   882.120155
1                  sk_lr   786.039632   881.334800
2               my_Lasso   786.176135   881.199352
3               sk_Lasso   786.149790   880.791767
4               my_Ridge   786.617639   870.881448
5               sk_Ridge   785.955878   881.692145
6          my_ElasticNet   892.778446   897.479246
7          sk_ElasticNet   894.535637   899.007504
8           MinMax_my_lr   793.150707   911.444518
9        MinMax_my_Ridge   858.662689   854.170043
10       MinMax_my_Lasso   795.537282   894.921134
11  MinMax_my_ElasticNet  1068.253142  1063.953432

In [48]:
R2_scores

                   model     train      test
0                  my_lr  0.511039  0.381255
1                  sk_lr  0.510983  0.382357
2               my_Lasso  0.510813  0.382546
3               sk_Lasso  0.510846  0.383117
4               my_Ridge  0.510263  0.396921
5               sk_Ridge  0.511087  0.381856
6          my_ElasticNet  0.369155  0.359521
7          sk_ElasticNet  0.366669  0.357338
8           MinMax_my_lr  0.502095  0.339434
9        MinMax_my_Ridge  0.416447  0.419844
10       MinMax_my_Lasso  0.499094  0.363167
11  MinMax_my_ElasticNet  0.096800  0.099878

## Standart

In [49]:
for name, model in models.items():
    model.fit(st_scaled_x_train, y_train)

    y_pred_train = model.predict(st_scaled_x_train)
    y_pred_test = model.predict(st_scaled_x_test)

    MAE_scores.loc[len(MAE_scores)] = [f"Standart_{name}", MAE(y_train, y_pred_train), MAE(y_test, y_pred_test)]
    RMSE_scores.loc[len(RMSE_scores)] = [f"Standart_{name}", RMSE(y_train, y_pred_train), RMSE(y_test, y_pred_test)]
    R2_scores.loc[len(R2_scores)] = [f"Standart_{name}", R2(y_train, y_pred_train), R2(y_test, y_pred_test)]

In [50]:
RMSE_scores

                     model        train         test
0                    my_lr   785.994621   882.120155
1                    sk_lr   786.039632   881.334800
2                 my_Lasso   786.176135   881.199352
3                 sk_Lasso   786.149790   880.791767
4                 my_Ridge   786.617639   870.881448
5                 sk_Ridge   785.955878   881.692145
6            my_ElasticNet   892.778446   897.479246
7            sk_ElasticNet   894.535637   899.007504
8             MinMax_my_lr   793.150707   911.444518
9          MinMax_my_Ridge   858.662689   854.170043
10         MinMax_my_Lasso   795.537282   894.921134
11    MinMax_my_ElasticNet  1068.253142  1063.953432
12          Standart_my_lr   785.981387   838.342628
13       Standart_my_Ridge   786.020443   838.475340
14       Standart_my_Lasso   786.022646   838.424969
15  Standart_my_ElasticNet   831.541049   875.487888

In [51]:
RMSE_scores

                     model        train         test
0                    my_lr   785.994621   882.120155
1                    sk_lr   786.039632   881.334800
2                 my_Lasso   786.176135   881.199352
3                 sk_Lasso   786.149790   880.791767
4                 my_Ridge   786.617639   870.881448
5                 sk_Ridge   785.955878   881.692145
6            my_ElasticNet   892.778446   897.479246
7            sk_ElasticNet   894.535637   899.007504
8             MinMax_my_lr   793.150707   911.444518
9          MinMax_my_Ridge   858.662689   854.170043
10         MinMax_my_Lasso   795.537282   894.921134
11    MinMax_my_ElasticNet  1068.253142  1063.953432
12          Standart_my_lr   785.981387   838.342628
13       Standart_my_Ridge   786.020443   838.475340
14       Standart_my_Lasso   786.022646   838.424969
15  Standart_my_ElasticNet   831.541049   875.487888

In [52]:
R2_scores

                     model     train      test
0                    my_lr  0.511039  0.381255
1                    sk_lr  0.510983  0.382357
2                 my_Lasso  0.510813  0.382546
3                 sk_Lasso  0.510846  0.383117
4                 my_Ridge  0.510263  0.396921
5                 sk_Ridge  0.511087  0.381856
6            my_ElasticNet  0.369155  0.359521
7            sk_ElasticNet  0.366669  0.357338
8             MinMax_my_lr  0.502095  0.339434
9          MinMax_my_Ridge  0.416447  0.419844
10         MinMax_my_Lasso  0.499094  0.363167
11    MinMax_my_ElasticNet  0.096800  0.099878
12          Standart_my_lr  0.511055  0.441145
13       Standart_my_Ridge  0.511006  0.440968
14       Standart_my_Lasso  0.511004  0.441035
15  Standart_my_ElasticNet  0.452729  0.390524

# PolyFeatures

In [53]:
from sklearn.preprocessing import PolynomialFeatures

In [54]:
poly = PolynomialFeatures()
poly = PolynomialFeatures(degree=10, interaction_only=True)
poly_train = poly.fit_transform(x_train[["bathrooms", "bedrooms"]])

poly_test = poly.transform(x_test[["bathrooms", "bedrooms"]])
# poly_train = sk_standart.fit_transform(poly_train)
# poly_test  = sk_standart.transform(poly_test)
poly_train

array([[1., 1., 1., 1.],
       [1., 1., 2., 2.],
       [1., 1., 2., 2.],
       ...,
       [1., 1., 1., 1.],
       [1., 1., 2., 2.],
       [1., 1., 3., 3.]], shape=(44612, 4))

In [55]:
pd.DataFrame(poly_train).isna().sum()

0    0
1    0
2    0
3    0
dtype: int64

In [56]:
for name, model in models.items():
    model.fit(poly_train, y_train)

    y_pred_train = model.predict(poly_train)
    y_pred_test = model.predict(poly_test)

    MAE_scores.loc[len(MAE_scores)] = [f"Poly_{name}", MAE(y_train, y_pred_train), MAE(y_test, y_pred_test)]
    RMSE_scores.loc[len(RMSE_scores)] = [f"Poly_{name}", RMSE(y_train, y_pred_train), RMSE(y_test, y_pred_test)]
    R2_scores.loc[len(R2_scores)] = [f"Poly_{name}", R2(y_train, y_pred_train), R2(y_test, y_pred_test)]

# Naive

In [57]:
y_mean, y_median = float(y_train.mean()), float(y_train.median())

baselines = {
    "baseline_mean": y_mean,
    "baseline_median": y_median,
}

tables = {
    "MAE": (MAE_scores, MAE),
    "RMSE": (RMSE_scores, RMSE),
    "R2": (R2_scores, R2),
}

for bname, c in baselines.items():
    tr = np.full(len(y_train), c)
    te = np.full(len(y_test), c)
    for _, (df, metric) in tables.items():
        df.loc[len(df)] = [bname, metric(y_train, tr), metric(y_test, te)]

In [58]:
MAE_scores

                     model       train        test
0                    my_lr  594.907434  600.012409
1                    sk_lr  593.250954  598.410908
2                 my_Lasso  595.146849  600.411714
3                 sk_Lasso  594.303256  599.583917
4                 my_Ridge  596.316804  601.409992
5                 sk_Ridge  594.060545  599.192951
6            my_ElasticNet  701.097048  703.729158
7            sk_ElasticNet  699.633142  702.186705
8             MinMax_my_lr  603.465182  683.826811
9          MinMax_my_Ridge  663.750293  663.398592
10         MinMax_my_Lasso  605.809775  669.616592
11    MinMax_my_ElasticNet  847.943197  846.829994
12          Standart_my_lr  594.050367  609.852921
13       Standart_my_Ridge  594.326603  610.456614
14       Standart_my_Lasso  594.137341  610.105440
15  Standart_my_ElasticNet  646.524391  669.725859
16              Poly_my_lr  660.710225  666.849591
17           Poly_my_Ridge  661.845193  668.135128
18           Poly_my_Lasso  660.842284  667.019460
19      Poly_my_ElasticNet  680.500606  685.995020
20           baseline_mean  891.250834  890.687588
21         baseline_median  869.131467  868.521055

In [59]:
RMSE_scores

                     model        train         test
0                    my_lr   785.994621   882.120155
1                    sk_lr   786.039632   881.334800
2                 my_Lasso   786.176135   881.199352
3                 sk_Lasso   786.149790   880.791767
4                 my_Ridge   786.617639   870.881448
5                 sk_Ridge   785.955878   881.692145
6            my_ElasticNet   892.778446   897.479246
7            sk_ElasticNet   894.535637   899.007504
8             MinMax_my_lr   793.150707   911.444518
9          MinMax_my_Ridge   858.662689   854.170043
10         MinMax_my_Lasso   795.537282   894.921134
11    MinMax_my_ElasticNet  1068.253142  1063.953432
12          Standart_my_lr   785.981387   838.342628
13       Standart_my_Ridge   786.020443   838.475340
14       Standart_my_Lasso   786.022646   838.424969
15  Standart_my_ElasticNet   831.541049   875.487888
16              Poly_my_lr   864.332457   989.218856
17           Poly_my_Ridge   866.390949   992.605498
18           Poly_my_Lasso   864.422329   990.215494
19      Poly_my_ElasticNet   883.716874   959.558446
20           baseline_mean  1124.041342  1121.438846
21         baseline_median  1147.836613  1144.361683

In [60]:
R2_scores

                     model     train      test
0                    my_lr  0.511039  0.381255
1                    sk_lr  0.510983  0.382357
2                 my_Lasso  0.510813  0.382546
3                 sk_Lasso  0.510846  0.383117
4                 my_Ridge  0.510263  0.396921
5                 sk_Ridge  0.511087  0.381856
6            my_ElasticNet  0.369155  0.359521
7            sk_ElasticNet  0.366669  0.357338
8             MinMax_my_lr  0.502095  0.339434
9          MinMax_my_Ridge  0.416447  0.419844
10         MinMax_my_Lasso  0.499094  0.363167
11    MinMax_my_ElasticNet  0.096800  0.099878
12          Standart_my_lr  0.511055  0.441145
13       Standart_my_Ridge  0.511006  0.440968
14       Standart_my_Lasso  0.511004  0.441035
15  Standart_my_ElasticNet  0.452729  0.390524
16              Poly_my_lr  0.408715  0.221890
17           Poly_my_Ridge  0.405895  0.216553
18           Poly_my_Lasso  0.408592  0.220322
19      Poly_my_ElasticNet  0.381896  0.267852
20           baseline_mean  0.000000 -0.000017
21         baseline_median -0.042787 -0.041316

# FINAL

In [61]:
pd.set_option("display.max_rows", None)
final_scores = pd.concat(
    [
        MAE_scores.assign(metric="MAE"),
        RMSE_scores.assign(metric="RMSE"),
        R2_scores.assign(metric="R2"),
    ],
    ignore_index=True,)[["metric", "model", "train", "test"]]
final_scores

   metric                   model        train         test
0     MAE                   my_lr   594.907434   600.012409
1     MAE                   sk_lr   593.250954   598.410908
2     MAE                my_Lasso   595.146849   600.411714
3     MAE                sk_Lasso   594.303256   599.583917
4     MAE                my_Ridge   596.316804   601.409992
5     MAE                sk_Ridge   594.060545   599.192951
6     MAE           my_ElasticNet   701.097048   703.729158
7     MAE           sk_ElasticNet   699.633142   702.186705
8     MAE            MinMax_my_lr   603.465182   683.826811
9     MAE         MinMax_my_Ridge   663.750293   663.398592
10    MAE         MinMax_my_Lasso   605.809775   669.616592
11    MAE    MinMax_my_ElasticNet   847.943197   846.829994
12    MAE          Standart_my_lr   594.050367   609.852921
13    MAE       Standart_my_Ridge   594.326603   610.456614
14    MAE       Standart_my_Lasso   594.137341   610.105440
15    MAE  Standart_my_ElasticNet   646.524391   669.725859
16    MAE              Poly_my_lr   660.710225   666.849591
17    MAE           Poly_my_Ridge   661.845193   668.135128
18    MAE           Poly_my_Lasso   660.842284   667.019460
19    MAE      Poly_my_ElasticNet   680.500606   685.995020
20    MAE           baseline_mean   891.250834   890.687588
21    MAE         baseline_median   869.131467   868.521055
22   RMSE                   my_lr   785.994621   882.120155
23   RMSE                   sk_lr   786.039632   881.334800
24   RMSE                my_Lasso   786.176135   881.199352
25   RMSE                sk_Lasso   786.149790   880.791767
26   RMSE                my_Ridge   786.617639   870.881448
27   RMSE                sk_Ridge   785.955878   881.692145
28   RMSE           my_ElasticNet   892.778446   897.479246
29   RMSE           sk_ElasticNet   894.535637   899.007504
30   RMSE            MinMax_my_lr   793.150707   911.444518
31   RMSE         MinMax_my_Ridge   858.662689   854.170043
32   RMSE         MinMax_my_Lasso   795.537282   894.921134
33   RMSE    MinMax_my_ElasticNet  1068.253142  1063.953432
34   RMSE          Standart_my_lr   785.981387   838.342628
35   RMSE       Standart_my_Ridge   786.020443   838.475340
36   RMSE       Standart_my_Lasso   786.022646   838.424969
37   RMSE  Standart_my_ElasticNet   831.541049   875.487888
38   RMSE              Poly_my_lr   864.332457   989.218856
39   RMSE           Poly_my_Ridge   866.390949   992.605498
40   RMSE           Poly_my_Lasso   864.422329   990.215494
41   RMSE      Poly_my_ElasticNet   883.716874   959.558446
42   RMSE           baseline_mean  1124.041342  1121.438846
43   RMSE         baseline_median  1147.836613  1144.361683
44     R2                   my_lr     0.511039     0.381255
45     R2                   sk_lr     0.510983     0.382357
46     R2                my_Lasso     0.510813     0.382546
47     R2                sk_Lasso     0.510846     0.383117
48     R2                my_Ridge     0.510263     0.396921
49     R2                sk_Ridge     0.511087     0.381856
50     R2           my_ElasticNet     0.369155     0.359521
51     R2           sk_ElasticNet     0.366669     0.357338
52     R2            MinMax_my_lr     0.502095     0.339434
53     R2         MinMax_my_Ridge     0.416447     0.419844
54     R2         MinMax_my_Lasso     0.499094     0.363167
55     R2    MinMax_my_ElasticNet     0.096800     0.099878
56     R2          Standart_my_lr     0.511055     0.441145
57     R2       Standart_my_Ridge     0.511006     0.440968
58     R2       Standart_my_Lasso     0.511004     0.441035
59     R2  Standart_my_ElasticNet     0.452729     0.390524
60     R2              Poly_my_lr     0.408715     0.221890
61     R2           Poly_my_Ridge     0.405895     0.216553
62     R2           Poly_my_Lasso     0.408592     0.220322
63     R2      Poly_my_ElasticNet     0.381896     0.267852
64     R2           baseline_mean     0.000000    -0.000017
65     R2         baseline_median    -0.042787    -0.041316

In [62]:

wide = (
    final_scores
    .set_index(["model", "metric"])[["train", "test"]]
    .unstack("metric")
)

wide.columns = wide.columns.swaplevel(0, 1)
wide = wide.sort_index(axis=1, level=0)

wide

metric                         MAE                    R2            \
                              test       train      test     train
model
MinMax_my_ElasticNet    846.829994  847.943197  0.099878  0.096800
MinMax_my_Lasso         669.616592  605.809775  0.363167  0.499094
MinMax_my_Ridge         663.398592  663.750293  0.419844  0.416447
MinMax_my_lr            683.826811  603.465182  0.339434  0.502095
Poly_my_ElasticNet      685.995020  680.500606  0.267852  0.381896
Poly_my_Lasso           667.019460  660.842284  0.220322  0.408592
Poly_my_Ridge           668.135128  661.845193  0.216553  0.405895
Poly_my_lr              666.849591  660.710225  0.221890  0.408715
Standart_my_ElasticNet  669.725859  646.524391  0.390524  0.452729
Standart_my_Lasso       610.105440  594.137341  0.441035  0.511004
Standart_my_Ridge       610.456614  594.326603  0.440968  0.511006
Standart_my_lr          609.852921  594.050367  0.441145  0.511055
baseline_mean           890.687588  891.250834 -0.000017  0.000000
baseline_median         868.521055  869.131467 -0.041316 -0.042787
my_ElasticNet           703.729158  701.097048  0.359521  0.369155
my_Lasso                600.411714  595.146849  0.382546  0.510813
my_Ridge                601.409992  596.316804  0.396921  0.510263
my_lr                   600.012409  594.907434  0.381255  0.511039
sk_ElasticNet           702.186705  699.633142  0.357338  0.366669
sk_Lasso                599.583917  594.303256  0.383117  0.510846
sk_Ridge                599.192951  594.060545  0.381856  0.511087
sk_lr                   598.410908  593.250954  0.382357  0.510983

metric                         RMSE
                               test        train
model
MinMax_my_ElasticNet    1063.953432  1068.253142
MinMax_my_Lasso          894.921134   795.537282
MinMax_my_Ridge          854.170043   858.662689
MinMax_my_lr             911.444518   793.150707
Poly_my_ElasticNet       959.558446   883.716874
Poly_my_Lasso            990.215494   864.422329
Poly_my_Ridge            992.605498   866.390949
Poly_my_lr               989.218856   864.332457
Standart_my_ElasticNet   875.487888   831.541049
Standart_my_Lasso        838.424969   786.022646
Standart_my_Ridge        838.475340   786.020443
Standart_my_lr           838.342628   785.981387
baseline_mean           1121.438846  1124.041342
baseline_median         1144.361683  1147.836613
my_ElasticNet            897.479246   892.778446
my_Lasso                 881.199352   786.176135
my_Ridge                 870.881448   786.617639
my_lr                    882.120155   785.994621
sk_ElasticNet            899.007504   894.535637
sk_Lasso                 880.791767   786.149790
sk_Ridge                 881.692145   785.955878
sk_lr                    881.334800   786.039632


### Best model  
- Standart_my_lr (поразительно, обычная линейка)))

### Most stable model
- Standart_my_lr (и тут она хи-хи)

# Additional

In [63]:
y_train_log = np.log1p(y_train)
y_test_log  = np.log1p(y_test)

my_lr.fit(st_scaled_x_train, y_train_log)

pred_train = np.expm1(my_lr.predict(st_scaled_x_train))
pred_test  = np.expm1(my_lr.predict(st_scaled_x_test))

In [64]:
print("MAE :", MAE(y_train, pred_train),  MAE(y_test, pred_test))
print("RMSE :", RMSE(y_train, pred_train), RMSE(y_test, pred_test))
print("R2  :", R2(y_train, pred_train),   R2(y_test, pred_test))

MAE : 590.7735295662677 153747.41459663626
RMSE : 800.5806943563176 39778016.499064885
R2  : 0.49272243407345495 -1258178449.1387937

### Почему выбросы удаляют только из train, а не из test
Test нужен как честная проверка, на чистых данных
Если удалить выбросы из test, то мы искусственно улучшим оценку качества, что я собсна и сделал)) По сути создав утечку

Ну и логарифмирование таргета здесь не подошло: на train норм, но на test несколько завышенных предсказаний после expm1 вскрылись и убили MAE/RMSE/R2, поэтому предлагаю тоже вскрыться