In [1]:
import pandas as pd

## 1. Reading Json and setting index

In [2]:
df =pd.read_json("../ex02/auto.json")
df.set_index('CarNumber', inplace = True)
df

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
E432XX77RUS        1   6500.000000  Toyota    Camry
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[725 rows x 4 columns]

## 2. Some selections

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 725 entries, Y163O8161RUS to H419XE197RUS
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Refund  725 non-null    int64
 1   Fines   725 non-null    float64
 2   Make    725 non-null    object
 3   Model   725 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 28.3+ KB

- *Fines* > 2100

In [6]:
df.loc[df["Fines"] > 2100]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]

- *Fines* > 2100 and *Refund* = 2

In [8]:
df.loc[(df["Fines"] > 2100) & (df["Refund"] == 2)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

- Models ffrom list

In [14]:
df.loc[df["Model"].isin(['Focus', 'Corolla'])]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

- Numbers from list

In [17]:
df.loc[df.index.isin(['Y7689C197RUS', '92928M178RU ', '7788KT197RU ', 'H115YO163RU ', 'X758HY197RU '])]

              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS       1  27000.0  Ford  Focus
Y7689C197RUS       2   9000.0  Ford  Focus
Y7689C197RUS       2  45000.0  Ford  Focus
Y7689C197RUS       1  36000.0  Ford  Focus

# 3. Aggregations with make_n_models

In [18]:
df.groupby('Make')['Fines'].median()

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

In [19]:
df.groupby(['Make', 'Model'])['Fines'].median()

Make        Model
Audi                   4200.0
BMW                    6500.0
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen             7400.0
            Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Volvo                  8500.0
Name: Fines, dtype: float64

In [20]:
df.groupby(['Make', 'Model'])['Fines'].count()

Make        Model
Audi                     1
BMW                      3
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen               3
            Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Volvo                    2
Name: Fines, dtype: int64

In [21]:
df.groupby(['Make', 'Model'])['Fines'].agg(['min', 'max'])

                       min            max
Make       Model
Audi                4200.0    4200.000000
BMW                 3000.0    8594.586466
Ford       Focus     100.0  180000.000000
           Mondeo   1100.0   46200.000000
Skoda      Octavia   300.0  145000.000000
Toyota     Camry     500.0   22400.000000
           Corolla   900.0   34300.000000
Volkswagen          1300.0    7900.000000
           Golf      200.0  168000.000000
           Jetta     500.0   46000.000000
           Passat    100.0   29700.000000
           Touareg   500.0    8594.586466
Volvo               6800.0   10200.000000

In [22]:
df.groupby(['Make', 'Model'])['Fines'].std()

Make        Model
Audi                            NaN
BMW                     2826.561226
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen              3674.688195
            Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Volvo                   2404.163056
Name: Fines, dtype: float64

## 4. Aggs with numbers

In [34]:
df

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
E432XX77RUS        1   6500.000000  Toyota    Camry
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[725 rows x 4 columns]

In [86]:
# sorted(df.groupby("Fines").groups.items(), reverse = True)
# df.groupby("Fines").apply(lambda x: x.index.tolist()).sort_index(ascending=False)
df.groupby("CarNumber").size().sort_values(ascending=False)

CarNumber
7788KT197RUS    4
92928M178RUS    4
Y7689C197RUS    4
7830C8197RUS    3
H387TM197RUS    3
               ..
Y965O8197RUS    1
9470EX178RUS    1
Y967O8197RUS    1
9474EX178RUS    1
7064C8197RUS    1
Length: 531, dtype: int64

In [87]:
df.loc["7788KT197RUS"]

              Refund         Fines  Make  Model
CarNumber
7788KT197RUS       2  12000.000000  Ford  Focus
7788KT197RUS       2   8594.586466  Ford  Focus
7788KT197RUS       1  20000.000000  Ford  Focus
7788KT197RUS       2   4000.000000  Ford  Focus

In [75]:
df.groupby("CarNumber")["Fines"].sum().sort_values(ascending=False)

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
Y195O8161RUS       100.0
C58078163RUS       100.0
K326T8197RUS       100.0
K376HE161RUS       100.0
83218C154RUS       100.0
Name: Fines, Length: 531, dtype: float64

In [88]:
df.loc["X758HY197RUS"]

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

In [ ]:
df.loc[df.groupby("CarNumber")["Model"].nunique() > 1]

              Refund   Fines        Make    Model
CarNumber
E316EH197RUS       1  1300.0  Volkswagen
E316EH197RUS       1  1300.0  Volkswagen  Touareg

In [103]:
df.loc["E316EH197RUS"]

              Refund   Fines        Make    Model
CarNumber
E316EH197RUS       1  1300.0  Volkswagen
E316EH197RUS       1  1300.0  Volkswagen  Touareg

In [104]:
df.groupby("CarNumber")["Model"].nunique().reset_index(name="UniqueModels").query("UniqueModels > 1")

        CarNumber  UniqueModels
202  E316EH197RUS             2