In [1]:
import pandas as pd

## Reading .log
используемые аргументы для read_csv:
- "delimiter" таб как разделитель (при считывании).
- "skiprows" пропускаем две строки по индексам
- "skipfooter" фильтруем последние 2 строки
- "header" = None чтобы не читать первую строку как заголовок
- "names" названия для столбцов
- "index_cols" для выбора столбца на индексы

In [2]:
df = pd.read_csv("../data/feed-views.log", delimiter="\t", skiprows=[2,3], skipfooter=2, header=None, names = ["datetime", "user"], index_col='datetime')
df

/var/folders/ts/zy03tlpj0hs45ygzg74rq8jc0000gn/T/ipykernel_13452/1726747154.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df = pd.read_csv("../data/feed-views.log", delimiter="\t", skiprows=[2,3], skipfooter=2, header=None, names = ["datetime", "user"], index_col='datetime')

                                 user
datetime
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

## Rename index and output

In [3]:
df.index.name = "date_time"
df.head()

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [4]:
df.tail()

                                 user
date_time
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

In [5]:
df.count()

user    1072
dtype: int64

## Write to csv

In [6]:
df.to_csv("feed-views-semicolon.log", sep=";")

In [ ]:
df2 = df.to_csv("feed-views-semicolon.log", sep=";")